/*
  ========================================
  layout.tsx — 全ページ共通の外枠
  ========================================
  学ぶこと:
  - App Router では app/layout.tsx がルートレイアウト
  - children に「今表示するページ」が入る
  - metadata で <title> などを設定できる
*/

import type { Metadata } from "next";
import "./globals.css";

// サイト全体のメタ情報（ブラウザタブのタイトルなど）
export const metadata: Metadata = {
  title: "My Next.js App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  // React.ReactNode = 画面に出せるもの（要素、文字列、配列など）
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      {/*
        className に Tailwind のユーティリティを書く。
        p-4 = padding: 1rem
        この body の中に、page.tsx や users/[userId]/page.tsx が children として入る。
      */}
      <body className="p-4">{children}</body>
    </html>
  );
}
